/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miner.view;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import miner.control.ImportClassesControl;
import miner.model.service.Observer;
import miner.util.exception.ValidationException;

/**
 *
 * @author carloseduardoxp
 */
public class ImportClassesView extends javax.swing.JInternalFrame implements Observer, ActionListener {

    private final ImportClassesControl control;

    private Integer percentFinished;
    
    private String message;

    Timer timer;    
    /**
     * Creates new form RepositorioGitView
     */
    public ImportClassesView() {
        control = new ImportClassesControl();
        initComponents();
        lblMsg.setText("");
    }

    public ImportClassesControl getControl() {
        return control;
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        prbImport.setValue(percentFinished);
        lblMsg.setText((message==null?"":message)+" "+percentFinished+"%");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblProject = new javax.swing.JLabel();
        cmbProject = new javax.swing.JComboBox<>();
        btnImport = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        prbImport = new javax.swing.JProgressBar();

        setClosable(true);
        setTitle("Import Classes");

        lblProject.setText("Project:");

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${control.projects}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cmbProject);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${control.selectedProject}"), cmbProject, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        lblMsg.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProject, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnImport)
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prbImport, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProject)
                    .addComponent(cmbProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnImport)
                .addGap(29, 29, 29)
                .addComponent(lblMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prbImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        percentFinished = 0;

        if (this.timer == null) {
            this.timer = new Timer(50, this);
        }

        if (!this.timer.isRunning()) {
            new Thread(new Runnable() {

                public void run() {
                    btnImport.setEnabled(false);
                    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    prbImport.setValue(0);
                    ImportClassesView view = ImportClassesView.this;
                    timer.start();
                    try {
                        long tempoInicial = System.currentTimeMillis();
                        control.importClasses(view);
                        JOptionPane.showMessageDialog(view,
                            "Finished in " + ((System.currentTimeMillis() - tempoInicial) / 1000) + " seconds",
                            "Import Classes",
                            JOptionPane.INFORMATION_MESSAGE);
                    } catch (ValidationException e) {
                        JOptionPane.showMessageDialog(view,
                            "Validation Fault: " + e.getMessage(),
                            "Field Validation",
                            JOptionPane.WARNING_MESSAGE);
                        e.printStackTrace();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(view,
                            "System error: " + e.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                        e.printStackTrace();
                    }
                    timer.stop();
                    btnImport.setEnabled(true);
                    setCursor(null);
                }
            }).start();
        }
    }//GEN-LAST:event_btnImportActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImport;
    private javax.swing.JComboBox<String> cmbProject;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblProject;
    private javax.swing.JProgressBar prbImport;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void sendStatusMessage(String message) {
        this.message = message;
    }

    @Override
    public void sendCurrentPercent(Integer percent) {
        this.percentFinished = percent;
    }

}
