SELECT CCC.CD_CLASS,CCC.CD_COMMIT_CHANGE,CCC.LOC,CCC.LCOM1,LCOM5,LCOM2,C.DT_COMMITTER_DATE,
       (SELECT GROUP_CONCAT(NM_DETECTED_SMELL) FROM TB_DETECTED_SMELL DS
	   WHERE DS.CD_CLASS = CCC.CD_CLASS AND DS.CD_COMMIT_CHANGE = CCC.CD_COMMIT_CHANGE)
       AS SMELLS,
       (SELECT GROUP_CONCAT(DS_OBSERVACAO) FROM TB_DETECTED_SMELL DS
	   WHERE DS.CD_CLASS = CCC.CD_CLASS AND DS.CD_COMMIT_CHANGE = CCC.CD_COMMIT_CHANGE)
       AS OBS,
       concat('C:/Mestrado/commits/JCommon/master/',cc.ds_hash,'/',cc.nm_new_filename),CCC.*
FROM TB_CLASS_COMMIT_CHANGE CCC,TB_COMMIT_CHANGE CC,TB_COMMIT C
WHERE CD_CLASS = 1109
  AND CCC.CD_COMMIT_CHANGE = CC.CD_COMMIT_CHANGE
  AND CC.DS_HASH = C.DS_HASH
ORDER BY C.DT_COMMITTER_DATE;
