drop temporary table table2

CREATE TEMPORARY TABLE IF NOT EXISTS table2 AS (
SELECT CD_DETECTED_SMELL
FROM TB_DETECTED_SMELL
WHERE CD_DETECTED_SMELL NOT IN (
SELECT MAX(CD_DETECTED_SMELL)
FROM TB_DETECTED_SMELL
GROUP BY NM_DETECTED_SMELL,CD_CLASS,CD_COMMIT_CHANGE
)
ORDER BY CD_DETECTED_SMELL
);

ALTER TABLE table2 ADD INDEX (CD_DETECTED_SMELL); # Does not require an index name

DELETE
FROM TB_DETECTED_SMELL
WHERE CD_DETECTED_SMELL IN (select CD_DETECTED_SMELL from table2);

